daemon off;

worker_processes 4;
pid /tmp/nginx.pid;

events { worker_connections 1024; }

http {
    server {
    	large_client_header_buffers 4 32k;

        listen 8080;
        root  /opt/nginx/html;
        include /opt/nginx/conf/mime.types;

        location / {
            try_files $uri /index.html;
        }
    }
}
